ifndef CONTIKI
  ${error CONTIKI not defined! Do not forget to source /upb/groups/fg-ccs/public/share/nes/2018w/env.sh}
endif

ifndef TARGET
TARGET=sky
endif

all: energy.sky

energy.upload: energy.upload

energy.sim: energy.csc energy.c
	java -jar $(CONTIKI)/tools/cooja/dist/cooja.jar -quickstart=energy.csc -contiki=$(CONTIKI)

simulation:
	java -jar $(CONTIKI)/tools/cooja/dist/cooja.jar -contiki=$(CONTIKI)

CONTIKI_WITH_IPV4 = 1
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
